version: '3.3'
services:
  app:
    build:
      context: .
    environment:
      - SERVER_PORT=3000
      - CI=true
    ports:
      - 8081:3000
    networks:
      - default
networks:
  default:
    driver: bridge
